"""valuation funm and risk scores

Revision ID: 10661d448b21
Revises: c9c15a698fc7
Create Date: 2026-09-24 16:41:47.195477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10661d448b21'
down_revision: Union[str, Sequence[str], None] = 'c9c15a698fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valuation_snapshot', sa.Column('funm_score', sa.Float(), nullable=True))
    op.add_column('valuation_snapshot', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valuation_snapshot', 'risk_score')
    op.drop_column('valuation_snapshot', 'funm_score')
    # ### end Alembic commands ###
