"""v0.6 structure state and base rate

Revision ID: 28bc328cd9e8
Revises: acc4a2b061f0
Create Date: 2026-09-27 23:49:40.520476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bc328cd9e8'
down_revision: Union[str, Sequence[str], None] = 'acc4a2b061f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_base_rate',
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=8), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('mean_ret', sa.Double(), nullable=True),
    sa.Column('median_ret', sa.Double(), nullable=True),
    sa.Column('p_positive', sa.Double(), nullable=True),
    sa.Column('mean_excess', sa.Double(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('state', 'regime', 'horizon')
    )
    op.create_table('structure_state_daily',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('upper', sa.Double(), nullable=True),
    sa.Column('lower', sa.Double(), nullable=True),
    sa.Column('levels', sa.JSON(), nullable=True),
    sa.Column('signal', sa.JSON(), nullable=True),
    sa.Column('weekly_state', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    op.create_index('ix_structure_state_daily_date_state', 'structure_state_daily', ['trade_date', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_structure_state_daily_date_state', table_name='structure_state_daily')
    op.drop_table('structure_state_daily')
    op.drop_table('structure_base_rate')
    # ### end Alembic commands ###
