"""float columns to double

Revision ID: 43b928ee059e
Revises: 10661d448b21
Create Date: 2026-09-24 18:28:07.512427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43b928ee059e'
down_revision: Union[str, Sequence[str], None] = '10661d448b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_trade', 'entry_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('backtest_trade', 'exit_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('backtest_trade', 'r_multiple',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('backtest_trade', 'pnl_pct',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('chan_signal', 'stop_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'target1',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'target2',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'strength',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'revenue',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'net_profit',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'revenue_yoy',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'profit_yoy',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'gross_margin',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'roe',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'debt_ratio',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'op_cashflow',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'goodwill',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'total_equity',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'total_assets',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('kline_daily', 'open',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'high',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'low',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'close',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'volume',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('kline_daily', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('kline_weekly', 'open',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'high',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'low',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'close',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'volume',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('kline_weekly', 'amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('market_env_daily', 'score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('market_env_daily', 'position_cap',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('position_event', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('position_plan', 'entry_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('position_plan', 'r_value',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('position_plan', 'initial_stop',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('position_plan', 'current_stop',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('position_plan', 'target1',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('position_plan', 'target2',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('position_plan', 'highest_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('position_plan', 'realized_pnl',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'chan_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'fund_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'sector_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'stop_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'target1',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'target2',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('recommend_run', 'position_cap',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'total_asset',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'cash',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'market_value',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'total_pnl',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_order', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
    op.alter_column('sim_order', 'filled_price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'cost',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'market_value',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'pnl',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'pnl_pct',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'pe_ttm',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'pb',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'roe_ttm',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'dividend_yield',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'total_mv',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'float_mv',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'comp_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'funm_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'risk_score',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valuation_snapshot', 'risk_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'funm_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'comp_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'float_mv',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'total_mv',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'dividend_yield',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'roe_ttm',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'pb',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('valuation_snapshot', 'pe_ttm',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'pnl_pct',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'pnl',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'market_value',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_position_snapshot', 'cost',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_order', 'filled_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_order', 'price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('sim_account_daily', 'total_pnl',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'market_value',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'cash',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('sim_account_daily', 'total_asset',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('recommend_run', 'position_cap',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'target2',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'target1',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'stop_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('recommend_item', 'price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'sector_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'fund_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'chan_score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('recommend_item', 'score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_plan', 'realized_pnl',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_plan', 'highest_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('position_plan', 'target2',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('position_plan', 'target1',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('position_plan', 'current_stop',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_plan', 'initial_stop',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_plan', 'r_value',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_plan', 'entry_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('position_event', 'price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('market_env_daily', 'position_cap',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('market_env_daily', 'score',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'amount',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('kline_weekly', 'volume',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('kline_weekly', 'close',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'low',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'high',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_weekly', 'open',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'amount',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('kline_daily', 'volume',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('kline_daily', 'close',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'low',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'high',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('kline_daily', 'open',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('fundamental_quarterly', 'total_assets',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'total_equity',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'goodwill',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'op_cashflow',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'debt_ratio',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'roe',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'gross_margin',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'profit_yoy',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'revenue_yoy',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'net_profit',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('fundamental_quarterly', 'revenue',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'strength',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'target2',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'target1',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'stop_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('chan_signal', 'price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('backtest_trade', 'pnl_pct',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('backtest_trade', 'r_multiple',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('backtest_trade', 'exit_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('backtest_trade', 'entry_price',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
