"""strategy on position plan and sim order

Revision ID: 97a294687275
Revises: 28a773a0f885
Create Date: 2026-09-29 10:17:46.385911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a294687275'
down_revision: Union[str, Sequence[str], None] = '28a773a0f885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_plan', sa.Column('strategy', sa.String(length=32), server_default='chan', nullable=False))
    op.add_column('sim_order', sa.Column('strategy', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sim_order', 'strategy')
    op.drop_column('position_plan', 'strategy')
    # ### end Alembic commands ###
