"""strategy signal daily

Revision ID: 9f75317b11a2
Revises: f257c7251ce1
Create Date: 2026-09-28 12:23:58.040998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f75317b11a2'
down_revision: Union[str, Sequence[str], None] = 'f257c7251ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_signal_daily',
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('strategy', 'code', 'trade_date')
    )
    op.create_index('ix_strategy_signal_daily_date', 'strategy_signal_daily', ['strategy', 'trade_date', 'zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_signal_daily_date', table_name='strategy_signal_daily')
    op.drop_table('strategy_signal_daily')
    # ### end Alembic commands ###
