"""v0.4 snapshots notify runtime state

Revision ID: acc4a2b061f0
Revises: c27774efb3f2
Create Date: 2026-09-25 21:25:07.954902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc4a2b061f0'
down_revision: Union[str, Sequence[str], None] = 'c27774efb3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('dedupe_key', sa.String(length=191), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('runtime_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stock_risk_label_daily',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code', 'label', 'snap_date')
    )
    op.create_index('ix_stock_risk_label_daily_date', 'stock_risk_label_daily', ['snap_date'], unique=False)
    op.create_table('stock_status_daily',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=4), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    op.create_index('ix_stock_status_daily_date', 'stock_status_daily', ['trade_date'], unique=False)
    op.add_column('fundamental_quarterly', sa.Column('first_seen', sa.Date(), nullable=True))
    op.add_column('stock_basic', sa.Column('first_seen', sa.Date(), nullable=True))
    op.add_column('stock_basic', sa.Column('last_seen', sa.Date(), nullable=True))
    op.add_column('stock_basic', sa.Column('missing_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('stock_basic', sa.Column('delisted_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###
    # 已有财报的可获得日期：法定披露截止日与实际拉取日期取早者
    op.execute("""
        UPDATE fundamental_quarterly SET first_seen = LEAST(DATE(updated_at), CASE DATE_FORMAT(report_date, '%m-%d')
            WHEN '03-31' THEN DATE(CONCAT(YEAR(report_date), '-04-30'))
            WHEN '06-30' THEN DATE(CONCAT(YEAR(report_date), '-08-31'))
            WHEN '09-30' THEN DATE(CONCAT(YEAR(report_date), '-10-31'))
            WHEN '12-31' THEN DATE(CONCAT(YEAR(report_date) + 1, '-04-30'))
            ELSE DATE_ADD(report_date, INTERVAL 120 DAY) END)
        WHERE first_seen IS NULL
    """)
    op.execute("UPDATE stock_basic SET first_seen = DATE(updated_at), last_seen = DATE(updated_at) WHERE active = 1 AND first_seen IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_basic', 'delisted_on')
    op.drop_column('stock_basic', 'missing_count')
    op.drop_column('stock_basic', 'last_seen')
    op.drop_column('stock_basic', 'first_seen')
    op.drop_column('fundamental_quarterly', 'first_seen')
    op.drop_index('ix_stock_status_daily_date', table_name='stock_status_daily')
    op.drop_table('stock_status_daily')
    op.drop_index('ix_stock_risk_label_daily_date', table_name='stock_risk_label_daily')
    op.drop_table('stock_risk_label_daily')
    op.drop_table('runtime_state')
    op.drop_table('notify_log')
    # ### end Alembic commands ###
