"""backtest_trade tags

Revision ID: c27774efb3f2
Revises: dec5b0073085
Create Date: 2026-09-24 20:31:08.013970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27774efb3f2'
down_revision: Union[str, Sequence[str], None] = 'dec5b0073085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_trade', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_trade', 'tags')
    # ### end Alembic commands ###
