"""initial schema

Revision ID: c9c15a698fc7
Revises: 
Create Date: 2026-09-24 14:32:44.498883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9c15a698fc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_sync_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_sync_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('by_signal', sa.JSON(), nullable=True),
    sa.Column('suggested_weights', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chan_signal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'level', 'signal_type', 'signal_date', name='uq_chan_signal')
    )
    op.create_index('ix_chan_signal_date', 'chan_signal', ['signal_date'], unique=False)
    op.create_table('chan_snapshot',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('data', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'level', 'calc_date')
    )
    op.create_table('fundamental_quarterly',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('revenue_yoy', sa.Float(), nullable=True),
    sa.Column('profit_yoy', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('op_cashflow', sa.Float(), nullable=True),
    sa.Column('goodwill', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'report_date')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_log_name', 'job_log', ['job_name', 'started_at'], unique=False)
    op.create_table('kline_daily',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    op.create_index('ix_kline_daily_date', 'kline_daily', ['trade_date'], unique=False)
    op.create_table('kline_weekly',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    op.create_index('ix_kline_weekly_date', 'kline_weekly', ['trade_date'], unique=False)
    op.create_table('market_env_daily',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('position_cap', sa.Float(), nullable=False),
    sa.Column('index_state', sa.JSON(), nullable=True),
    sa.Column('breadth', sa.JSON(), nullable=True),
    sa.Column('sectors', sa.JSON(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trade_date')
    )
    op.create_table('mcp_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args', sa.String(length=500), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcp_call_log_created', 'mcp_call_log', ['created_at'], unique=False)
    op.create_index('ix_mcp_call_log_tool', 'mcp_call_log', ['tool'], unique=False)
    op.create_table('mcp_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_info', sa.JSON(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_signal', sa.String(length=8), nullable=True),
    sa.Column('entry_signal_date', sa.Date(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('r_value', sa.Float(), nullable=False),
    sa.Column('initial_stop', sa.Float(), nullable=False),
    sa.Column('current_stop', sa.Float(), nullable=False),
    sa.Column('stop_source', sa.String(length=64), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('highest_price', sa.Float(), nullable=True),
    sa.Column('reduce_steps', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('linked_sim', sa.Boolean(), nullable=False),
    sa.Column('last_eval_date', sa.Date(), nullable=True),
    sa.Column('last_advice', sa.JSON(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_plan_status', 'position_plan', ['status'], unique=False)
    op.create_table('recommend_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('market_regime', sa.String(length=16), nullable=True),
    sa.Column('position_cap', sa.Float(), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=False),
    sa.Column('total_selected', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommend_run_run_date'), 'recommend_run', ['run_date'], unique=False)
    op.create_table('sim_account_daily',
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('snap_date')
    )
    op.create_table('sim_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_sim_order_code', 'sim_order', ['code'], unique=False)
    op.create_table('sim_position_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snap_date', 'code', name='uq_sim_pos_snap')
    )
    op.create_table('stock_basic',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('exchange', sa.String(length=4), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('industry_code', sa.String(length=32), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_index', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_stock_basic_industry', 'stock_basic', ['industry'], unique=False)
    op.create_table('strategy_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_progress',
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('task', 'code')
    )
    op.create_table('valuation_snapshot',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('roe_ttm', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('total_mv', sa.Float(), nullable=True),
    sa.Column('float_mv', sa.Float(), nullable=True),
    sa.Column('comp_score', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    op.create_index('ix_valuation_snapshot_date', 'valuation_snapshot', ['trade_date'], unique=False)
    op.create_table('watchlist',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('backtest_trade',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_trade_run', 'backtest_trade', ['run_id'], unique=False)
    op.create_table('position_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['position_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_event_plan', 'position_event', ['plan_id'], unique=False)
    op.create_table('recommend_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('chan_score', sa.Float(), nullable=False),
    sa.Column('fund_score', sa.Float(), nullable=False),
    sa.Column('sector_score', sa.Float(), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target1', sa.Float(), nullable=True),
    sa.Column('target2', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['recommend_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommend_item_run', 'recommend_item', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommend_item_run', table_name='recommend_item')
    op.drop_table('recommend_item')
    op.drop_index('ix_position_event_plan', table_name='position_event')
    op.drop_table('position_event')
    op.drop_index('ix_backtest_trade_run', table_name='backtest_trade')
    op.drop_table('backtest_trade')
    op.drop_table('watchlist')
    op.drop_index('ix_valuation_snapshot_date', table_name='valuation_snapshot')
    op.drop_table('valuation_snapshot')
    op.drop_table('sync_progress')
    op.drop_table('strategy_config')
    op.drop_index('ix_stock_basic_industry', table_name='stock_basic')
    op.drop_table('stock_basic')
    op.drop_table('sim_position_snapshot')
    op.drop_index('ix_sim_order_code', table_name='sim_order')
    op.drop_table('sim_order')
    op.drop_table('sim_account_daily')
    op.drop_index(op.f('ix_recommend_run_run_date'), table_name='recommend_run')
    op.drop_table('recommend_run')
    op.drop_index('ix_position_plan_status', table_name='position_plan')
    op.drop_table('position_plan')
    op.drop_table('mcp_credential')
    op.drop_index('ix_mcp_call_log_tool', table_name='mcp_call_log')
    op.drop_index('ix_mcp_call_log_created', table_name='mcp_call_log')
    op.drop_table('mcp_call_log')
    op.drop_table('market_env_daily')
    op.drop_index('ix_kline_weekly_date', table_name='kline_weekly')
    op.drop_table('kline_weekly')
    op.drop_index('ix_kline_daily_date', table_name='kline_daily')
    op.drop_table('kline_daily')
    op.drop_index('ix_job_log_name', table_name='job_log')
    op.drop_table('job_log')
    op.drop_table('fundamental_quarterly')
    op.drop_table('chan_snapshot')
    op.drop_index('ix_chan_signal_date', table_name='chan_signal')
    op.drop_table('chan_signal')
    op.drop_table('backtest_run')
    op.drop_table('app_sync_state')
    op.drop_table('app_sync_log')
    # ### end Alembic commands ###
