"""risk labels, recommend pool and tracking, backtest control

Revision ID: dec5b0073085
Revises: 43b928ee059e
Create Date: 2026-09-24 19:13:49.943456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec5b0073085'
down_revision: Union[str, Sequence[str], None] = '43b928ee059e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_risk_label',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'label')
    )
    op.create_index('ix_stock_risk_label_label', 'stock_risk_label', ['label'], unique=False)
    op.create_table('recommend_perf',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('signal_type', sa.String(length=8), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('pool', sa.String(length=8), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Double(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('ret5', sa.Double(), nullable=True),
    sa.Column('ret10', sa.Double(), nullable=True),
    sa.Column('ret20', sa.Double(), nullable=True),
    sa.Column('ex300_5', sa.Double(), nullable=True),
    sa.Column('ex300_10', sa.Double(), nullable=True),
    sa.Column('ex300_20', sa.Double(), nullable=True),
    sa.Column('ex1000_5', sa.Double(), nullable=True),
    sa.Column('ex1000_10', sa.Double(), nullable=True),
    sa.Column('ex1000_20', sa.Double(), nullable=True),
    sa.Column('max_drawdown', sa.Double(), nullable=True),
    sa.Column('first_hit', sa.String(length=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['recommend_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('ix_recommend_perf_run', 'recommend_perf', ['run_id'], unique=False)
    op.add_column('backtest_trade', sa.Column('scope', sa.String(length=8), nullable=True))
    op.add_column('backtest_trade', sa.Column('bench_ret', sa.Double(), nullable=True))
    op.add_column('backtest_trade', sa.Column('excess', sa.Double(), nullable=True))
    op.add_column('backtest_trade', sa.Column('segment', sa.String(length=8), nullable=True))
    op.add_column('backtest_trade', sa.Column('is_control', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('recommend_item', sa.Column('pool', sa.String(length=8), server_default='main', nullable=False))
    op.add_column('recommend_item', sa.Column('scope', sa.String(length=8), server_default='bi', nullable=False))
    op.add_column('recommend_item', sa.Column('confirmed', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('recommend_item', sa.Column('strong_div', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('recommend_item', sa.Column('avg_amount', sa.Double(), nullable=True))
    op.add_column('recommend_item', sa.Column('risk_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend_item', 'risk_labels')
    op.drop_column('recommend_item', 'avg_amount')
    op.drop_column('recommend_item', 'strong_div')
    op.drop_column('recommend_item', 'confirmed')
    op.drop_column('recommend_item', 'scope')
    op.drop_column('recommend_item', 'pool')
    op.drop_column('backtest_trade', 'is_control')
    op.drop_column('backtest_trade', 'segment')
    op.drop_column('backtest_trade', 'excess')
    op.drop_column('backtest_trade', 'bench_ret')
    op.drop_column('backtest_trade', 'scope')
    op.drop_index('ix_recommend_perf_run', table_name='recommend_perf')
    op.drop_table('recommend_perf')
    op.drop_index('ix_stock_risk_label_label', table_name='stock_risk_label')
    op.drop_table('stock_risk_label')
    # ### end Alembic commands ###
