"""价值池数据：不复权日线、分红、财报历史、条件选股快照

Revision ID: f257c7251ce1
Revises: 28bc328cd9e8
Create Date: 2026-09-28 10:37:33.653877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f257c7251ce1'
down_revision: Union[str, Sequence[str], None] = '28bc328cd9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_event',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('year', sa.String(length=8), nullable=True),
    sa.Column('cash', sa.Double(), nullable=False),
    sa.Column('bonus', sa.Double(), nullable=False),
    sa.Column('transfer', sa.Double(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'ex_date')
    )
    op.create_table('filter_snapshot',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('expression', sa.String(length=255), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'snap_date')
    )
    op.create_table('finance_history',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('publ_date', sa.Date(), nullable=True),
    sa.Column('roe', sa.Double(), nullable=True),
    sa.Column('roe_weighted', sa.Double(), nullable=True),
    sa.Column('eps_ttm', sa.Double(), nullable=True),
    sa.Column('np_ttm', sa.Double(), nullable=True),
    sa.Column('revenue_ttm', sa.Double(), nullable=True),
    sa.Column('dividend_ttm', sa.Double(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'report_date')
    )
    op.create_table('kline_daily_raw',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Double(), nullable=False),
    sa.Column('high', sa.Double(), nullable=False),
    sa.Column('low', sa.Double(), nullable=False),
    sa.Column('close', sa.Double(), nullable=False),
    sa.Column('volume', sa.Double(), nullable=True),
    sa.Column('amount', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('code', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kline_daily_raw')
    op.drop_table('finance_history')
    op.drop_table('filter_snapshot')
    op.drop_table('dividend_event')
    # ### end Alembic commands ###
