"""structure map and events

Revision ID: f65b84e122fd
Revises: 97a294687275
Create Date: 2026-09-29 10:23:18.303384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65b84e122fd'
down_revision: Union[str, Sequence[str], None] = '97a294687275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', 'event_type', name='uq_structure_event')
    )
    op.create_index('ix_structure_event_date', 'structure_event', ['trade_date'], unique=False)
    op.create_table('structure_map_daily',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Double(), nullable=True),
    sa.Column('upper', sa.Double(), nullable=True),
    sa.Column('lower', sa.Double(), nullable=True),
    sa.Column('ret5', sa.Double(), nullable=True),
    sa.Column('levels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('kind', 'key', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure_map_daily')
    op.drop_index('ix_structure_event_date', table_name='structure_event')
    op.drop_table('structure_event')
    # ### end Alembic commands ###
